### PR TITLE
Improves README

### PR DESCRIPTION
**Pull request by agrison**
Improves the README by explaining about `:conn-opts` and show a small example of `Boundary` implementation.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you change the commit message so it's "Improve" instead of "Improved", wrap the commit body at 72 characters, and remove the backticks?

I follow [the seven rules](https://chris.beams.io/posts/git-commit/#seven-rules) for my repositories.

**Comment by agrison** [comment]
done 👍

**Comment by weavejester** [comment]
Thanks! But you've written it with an extra "s" - it should be "Improve" instead of "Improves". Git commit subjects are written like commands (e.g. "Merge", "Revert", etc.).

**Comment by agrison** [comment]
done :)

**Pull request merged**
